"""
Contextual Retrieval Enricher
==============================
Implements Anthropic's "Contextual Retrieval" technique (October 2024).

Problem with standard chunking:
  When you split a document into 512-token chunks, each chunk loses
  the surrounding context needed to interpret it correctly.
  e.g. "The company reported 23% growth" — which company? what period?

Solution:
  Before embedding each chunk, prepend a short (50-100 token) context
  description generated by a small LLM. This description anchors the chunk
  in the document's broader context.

Reported improvement: 15–25% retrieval recall improvement on document Q&A.

Reference:
  Anthropic blog: "Introducing Contextual Retrieval" — October 2024
  https://www.anthropic.com/news/contextual-retrieval
"""
from __future__ import annotations
import logging

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

from app.core.state import AgentState
from app.core.config import settings

logger = logging.getLogger(__name__)

CONTEXT_SYSTEM = """You are a document processing assistant.
Given a chunk from a larger document and the document's title/beginning,
write a SHORT (2-3 sentence) context that situates this chunk within
the full document. Focus on:
- What section/topic this chunk belongs to
- Any key entities or time periods that a reader outside this chunk needs to know
Do NOT summarize the chunk itself. Only provide surrounding context.
Return ONLY the context sentences, nothing else."""


class ContextualEnricher:
    def __init__(self):
        self.llm = ChatOpenAI(
            model=settings.router_model,
            api_key=settings.openai_api_key,
            temperature=0.0,
            max_tokens=150,
        )

    def enrich_chunks(self, state: AgentState) -> AgentState:
        """
        LangGraph node: prepend contextual description to each chunk.
        Uses the first 500 words of the document as global context anchor.
        """
        chunks = state.get("chunks", [])
        if not chunks:
            return {}

        # Build document-level context anchor from first chunk
        doc_anchor = chunks[0]["text"][:500] if chunks else ""
        filename = chunks[0].get("filename", "document")

        enriched = []
        for chunk in chunks:
            context = self._generate_context(
                chunk_text=chunk["text"],
                doc_anchor=doc_anchor,
                filename=filename,
            )
            enriched_text = f"{context}\n\n{chunk['text']}" if context else chunk["text"]
            enriched.append({**chunk, "text": enriched_text, "context_prepended": True})

        logger.info("Contextual enricher: enriched %d chunks", len(enriched))
        return {"chunks": enriched}

    def _generate_context(self, chunk_text: str, doc_anchor: str, filename: str) -> str:
        """Generate a 2-3 sentence context description for a single chunk."""
        try:
            prompt = (
                f"Document: {filename}\n"
                f"Document beginning:\n{doc_anchor}\n\n"
                f"Chunk to contextualize:\n{chunk_text[:800]}"
            )
            resp = self.llm.invoke([
                SystemMessage(content=CONTEXT_SYSTEM),
                HumanMessage(content=prompt),
            ])
            return resp.content.strip()
        except Exception as e:
            logger.warning("Context generation failed for chunk (non-fatal): %s", e)
            return ""


contextual_enricher = ContextualEnricher()


def enrich_chunks(state: AgentState) -> AgentState:
    """Module-level function for LangGraph node registration."""
    return contextual_enricher.enrich_chunks(state)
